# Generated by Django 6.0.4 on 2026-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
