# Generated by Django 6.0.4 on 2026-04-15 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('MV', 'Movie'), ('TV', 'TV Show'), ('EP', 'Episode')], db_index=True, default='MV', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('genres', models.ManyToManyField(related_name='titles', to='titles.genre')),
                ('parent_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='titles.title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleCast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ACT', 'Actor'), ('DIR', 'Director'), ('WRT', 'Writer')], max_length=3)),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='people.person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='titles.title')),
            ],
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title', 'release_date'], name='titles_titl_title_5c939d_idx'),
        ),
        migrations.AddIndex(
            model_name='titlecast',
            index=models.Index(fields=['title', 'role'], name='titles_titl_title_i_96bf36_idx'),
        ),
        migrations.AddConstraint(
            model_name='titlecast',
            constraint=models.UniqueConstraint(fields=('title', 'person', 'role', 'character_name'), name='unique_cast_role'),
        ),
    ]
