# Generated by Django 6.0.4 on 2026-04-15 17:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='title',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='title_search_gin'),
        ),
    ]
