# Generated by Django 6.0.4 on 2026-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_search_vector_title_title_search_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
