# Generated by Django 6.0.4 on 2026-04-17 13:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_title_avg_rating'),
    ]

    operations = [
        TrigramExtension(),
    ]