# Generated by Django 6.0.4 on 2026-04-17 17:53

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_enable_trigram'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='title',
            name='titles_titl_title_5c939d_idx',
        ),
        migrations.RenameIndex(
            model_name='title',
            new_name='titles_titl_search__980535_gin',
            old_name='title_search_gin',
        ),
        migrations.AddField(
            model_name='title',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='title',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-popularity'], name='titles_titl_popular_dba050_idx'),
        ),
    ]
