# Generated by Django 6.0.4 on 2026-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_remove_title_titles_titl_title_5c939d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='trailer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
