# Generated by Django 6.0.4 on 2026-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_title_trailer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
